### ISSUE TITLE
Clear/direct vs. other types of metaphor

### ISSUE THREAD

**Issue by LemmensJens** [EducationalTestingService/metaphor#3]
Is there a way to acquire labels that distinguish between direct/clear metaphors and other types of metaphor?

Thanks!

**Comment by benbuleong** [comment]
Thanks for your question. Our research has so far focused on two major datasets i.e. VUA and TOEFL, so we'll answer you in that context. For VUA, the original annotation scheme does allow for  labeling of different metaphor subtypes, although we are not sure if the difference between them amounts to a direct/clear and less obvious metaphor for your research needs. You can see the actual annotation guideline used for VUA in this Steen et al (2010) [paper](https://scholar.google.com/scholar?cluster=9145312936156957510&hl=en&as_sdt=0,31). For TOEFL, we did not make an effort to create distinction between clear and dubious metaphors during labeling, nor do we have subtypes. There, the annotation is made by linguistically sophisticated close readers who aren’t however specialists in metaphor theory. You can also check out the annotation guideline in this Beigman Klebanov et al. (2018) [paper](https://www.aclweb.org/anthology/N18-2014.pdf).

**Comment by LemmensJens** [comment]
Dear,
Thank you for your quick response. The original VUA annotation scheme seems to meet my research needs, but if I'm not mistaken, these labels are not provided in all_pos_tokens.csv. Is it possible to obtain those labels elsewhere?

**Comment by benbuleong** [comment]
You can download the training labels for both allpos and verbs using this [link](https://github.com/EducationalTestingService/metaphor/releases/download/v1.0/naacl_flp_train_gold_labels.zip). We expect to release all test labels for both allpos and verbs at a later date in the Summer of 2020.

**Comment by LemmensJens** [comment]
These labels do not follow the original annotation scheme, is that correct?

**Comment by benbuleong** [comment]
In the original annotation of the VUA corpus, there are many subtypes available. For the shared task, we do have a configuration file that actually specifies what metaphor subtypes we filter from the corpus for the purpose of the shared task. You can download the starter kit [here](https://github.com/EducationalTestingService/metaphor/releases/download/v1.0/naacl_flp_starter_kit.zip), make changes to `setup.cfg` and run `vua_xml_parser` to get the subtype labels you need. However, you need to obtain for yourself a copy of `VUAMC.xml` due to licensing restrictions. Please contact the VUA metaphor team at [here](http://www.vismet.org/metcor/search/showPage.php?page=start).
